# Site settings
title: Craft Solution - IT Consulting Alen Tolj
email:
description: Craft Solution Landing Page, Portfolio und Blogging

baseurl: "/"
url: "https://atolj.github.io"

## Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/toljalen
  - title: google-plus
    url: https://plus.google.com/111769893704509866095
  - title: github
    url: https://github.com/atolj
  - title: linkedin
    url: https://de.linkedin.com/in/alen-tolj
  - title: xing
    url: https://www.xing.com/profile/Alen_Tolj

collections:
  - projects

sass:
  sass_dir: _scss
  style: compressed
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: [".idea","node_modules","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "my-site"
  - scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
